name: Build and Deploy .NET 8 App to Azure App Service

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DOTNET_VERSION: '8.0.x'  # .NET SDK version

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout source code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Setup .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      # 3️⃣ Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # 4️⃣ Build the project
      - name: Build
        run: dotnet build --configuration Release --no-restore

      # 5️⃣ Publish to output folder
      - name: Publish
        run: dotnet publish -c Release -o ./publish_output

      # 6️⃣ Deploy to Azure Web App
      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "ASPWebAppDemo"   # 👈 Replace with your App Service name
          slot-name: "production"             # Optional: use "staging" if applicable
          publish-profile: ${{ secrets.APP_PUBLISH_SECRET }}
          package: ./publish_output

